version: '3.7'
services:
  stream:
    build:
      context: ./stream
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - filesystem
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
  authentication:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SERVICE_URL: http://localhost:8080
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  upload:
    build: 
      context: ./upload
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
      FILESYSTEM_URL: http://filesystem:8100
    depends_on:
      - mysql
  filesystem:
    build:
      context: ./filesystem
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - file-data:/app/uploads
volumes:
  mysql-data:
  file-data:
