version: '3.7'
services:
  authentication:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  upload:
    build: 
      context: ./upload
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
