CREATE DATABASE IF NOT EXISTS videodb;
USE videodb;

CREATE TABLE IF NOT EXISTS videos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    path VARCHAR(255)
);

CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON videodb.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;